
## Albedo

$$
albedo = \alpha_{SW} = \frac{SW_{\uparrow}}{SW_{\downarrow}}
$${#eq-Albedo}

## Beers Law

$$
R_z = R_0 e^{-z\mu}
$${#eq-Beers-Law}

## LE Bowen

$$
LE = \frac{R_n-G}{1+B}
$${#eq-LE-Bowen}

## H Bowen

$$
H = \frac{R_n-G}{1+B^{-1}}
$${#eq-H-Bowen}

## Bowen Ratio

$$
B = \frac{H}{LE}
$${#eq-Bowen-Ratio}

## Bulk Transmissivity

$$
SW_\downarrow = I_{ex} \Psi_a^{m}
$${#eq-Bulk-Transmissivity}

## Conservation Equation Radiation

$$
\zeta_\lambda + \Psi_\lambda + \alpha_\lambda = 1
$${#eq-Conservation-Equation-Radiation}

## Conservation Law Scalar 1D

$$
\frac{dc}{dt} = \frac{\partial c}{\partial t} + w \frac{\partial c}{\partial z} 
$${#eq-Conservation-Law-Scalar-1D}

## Conservation Law Scalar Homogeneous 2

$$
\frac{dc}{dt} = \frac{\partial c}{\partial t} \color{white}{+ u \frac{\partial c}{\partial x} + v \frac{\partial c}{\partial y}} + w \frac{\partial c}{\partial z} 
$${#eq-Conservation-Law-Scalar-Homogeneous-2}

## Conservation Law Scalar Homogeneous

$$
\frac{dc}{dt} = \frac{\partial c}{\partial t} \color{gray}{+ u \frac{\partial c}{\partial x} + v \frac{\partial c}{\partial y}} + w \frac{\partial c}{\partial z} 
$${#eq-Conservation-Law-Scalar-Homogeneous}

## Conservation Law Scalar

$$
\frac{dc}{dt} = \frac{\partial c}{\partial t} + u \frac{\partial c}{\partial x} + v \frac{\partial c}{\partial y} + w \frac{\partial c}{\partial z} 
$${#eq-Conservation-Law-Scalar}

## Conservation Law Simplified

$$
In - Out = \Delta S
$${#eq-Conservation-Law-Simplified}

## Cosine Law of Illumination

$$
R_s = R_p cos(Z)
$${#eq-Cosine-Law-of-Illumination}

## Damping Depth

$$
D = \sqrt{\small\frac{2K}{\omega}} = \sqrt{\small\frac{KP}{\pi}}
$${#eq-Damping-Depth}

## Energy of Photon

$$
e = hv
$${#eq-Energy-of-Photon}

## Extraterrestrial Irradiance

$$
I_{ex}=I_0(\frac{R_{av}}{R})^2\cos(Z)
$${#eq-Extraterrestrial-Irradiance}

## Adjusted Constant

$$
\begin{eqnarray}(\frac{R_{av}}{R})^2 = & 1.00011+0.034221\cos(\gamma)+0.001280\sin(\gamma)+\\                     &0.000819\cos(2\gamma)+0.000077\sin(2\gamma)\end{eqnarray}
$${#eq-Adjusted-Constant}

## Fouriers Law

$$
H_G = -k \small\frac{T_2 - T_1}{z_2 - z_1}
$${#eq-Fouriers-Law}

## Frequency

$$
v=\frac{c}{\lambda}
$${#eq-Frequency}

## Heat Capacity Soil

$$
C_{s}=C_{m}\theta_{m}+C_{o}\theta_{o}+C_{w}\theta_{w}+C_{a}\theta_{a}
$${#eq-Heat-Capacity-Soil}

## Heat Sharing

$$
\frac{H_g}{H} = \frac{\mu_g}{\mu_a}
$${#eq-Heat-Sharing}

## Kelvin

$$
T(K) = T(\deg C) + 273.15
$${#eq-Kelvin}

## Kirchhoffs Law

$$
\zeta_{\lambda} = \epsilon_{\lambda}
$${#eq-Kirchhoffs-Law}

## Longwave Radiation Balance

$$
\zeta_{LW} + \alpha_{LW} = 1
$${#eq-Longwave-Radiation-Balance}

## Longwave Reflectivity

$$
\alpha_{LW} = 1 - \epsilon_{LW}
$${#eq-Longwave-Reflectivity}

## Long wave Flux Density Stefan Boltzman

$$
LW^* = LW\downarrow - \epsilon_{LW}\sigma_b T_s^4 -(1-\epsilon_{LW})LW\downarrow
$${#eq-Long-wave-Flux-Density-Stefan-Boltzman}

## Long wave Flux Density

$$
LW^* = LW\downarrow - LW\uparrow
$${#eq-Long-wave-Flux-Density}

## NDVI

$$
NDVI = \frac{NIR-Red}{NIR+Red}
$${#eq-NDVI}

## Absorbed SW

$$
SW^* = SW \downarrow (1 - \alpha)
$${#eq-Absorbed-SW}

## Net Absorbed Emitted LW

$$
LW^* = \epsilon LW \downarrow - \epsilon \sigma_b T_s^4
$${#eq-Net-Absorbed-Emitted-LW}

## Net Radiation Energy Balance

$$
R_n = SW \downarrow (1 - \alpha) + \epsilon LW \downarrow - \epsilon \sigma_b T_s^4
$${#eq-Net-Radiation-Energy-Balance}

## Net Radiation Short

$$
R_n = SW^* + LW^*
$${#eq-Net-Radiation-Short}

## Net Radiation

$$
R_n = (SW \downarrow - SW \uparrow) + (LW \downarrow - LW \uparrow)
$${#eq-Net-Radiation}

## Phase Shifted Sinusoidal Temperature Wave

$$
T_{(z,t)}=\overline{T_o}+\Delta T_o e^{-z(\small\frac{\omega}{2K})^{1/2}} \sin(\omega t - (\small\frac{\omega}{2K})^{1/2}z)
$${#eq-Phase-Shifted-Sinusoidal-Temperature-Wave}

## Planks Law

$$
E = \frac{2*h*c}{\lambda^{5}}*\frac{1}{e^{\frac{h*c}{\lambda*\sigma_b*T}}-1}
$${#eq-Planks-Law}

## Prata

$$
\epsilon_a = [1-(1+zeta)\exp{-(a+b\zeta)^{0.5}}]
$${#eq-Prata}

## Radiation Balance Air.qmd

$$
\Delta R_{n(\Delta z)}=R_{n(z+\Delta z)}-R_{n(z)}=C_a(\frac{\Delta T_a}{\Delta t})_R \Delta z
$${#eq-Radiation-Balance-Air.qmd}

## Reflectivity

$$
\alpha_\lambda = \frac{\lambda_{reflected}}{\lambda_{incident}}
$${#eq-Reflectivity}

## Reflectance Coefficient

$$
\alpha_{\lambda_1 \rightarrow \lambda_2} = \frac{\int_{\lambda_1}^{\lambda_2}\alpha_\lambda I_\lambda d_\lambda}{\int_{\lambda_1}^{\lambda_2}I_\lambda d_\lambda}
$${#eq-Reflectance-Coefficient}

## Relative Humidity

$$
RH=\frac{P_v}{P_v^*}
$${#eq-Relative-Humidity}

## Shear Stress

$$
\tau = \mu\small\frac{\delta u}{\delta z}
$${#eq-Shear-Stress}

## Sinusoidal Temperature Wave

$$
T_{(o,t)}=\overline{T_o}+\Delta T_o \sin(\omega t)
$${#eq-Sinusoidal-Temperature-Wave}

## Soil Heat Flux Divergence

$$
\small\frac{\Delta T_s}{\Delta t} =  \small\frac{1}{C_s}\small\frac{\Delta H_g}{\Delta z}
$${#eq-Soil-Heat-Flux-Divergence}

## Soil Heat Flux

$$
\frac{H_g}{z} = C_{s} \frac{\Delta T_{s}}{\Delta t}
$${#eq-Soil-Heat-Flux}

## Soil Volume Fractions

$$
\theta_a+\theta_w+\theta_g = 1
$${#eq-Soil-Volume-Fractions}

## Soil Volume Fractions

$$
\theta_P = \theta_a + \theta_w = 1 - \theta_g
$${#eq-Soil-Volume-Fractions}

## Organic Mineral

$$
\theta_g = \theta_m + \theta_o
$${#eq-Organic-Mineral}

## Solar Declination

$$
\begin{eqnarray}\delta = & 0.006918 - 0.399912 \cos( \gamma)+0.070257 \sin( \gamma)  \\         & -0.006758 \cos(2 \gamma) + 0.000907\sin(2\gamma) \nonumber \\         & -0.002697\cos(3\gamma)+0.00148 \sin(3\gamma) \nonumber \end{eqnarray}
$${#eq-Solar-Declination}

## Fractional Year

$$
\gamma = \frac{2 \pi }{365} (DOY-1) 
$${#eq-Fractional-Year}

## Solar Zenith

$$
\cos(Z) = \sin(\beta) = \sin(\Phi)\sin(\delta)+\cos(\Phi)\cos(\delta)\cos(h)
$${#eq-Solar-Zenith}

## Hour Angle

$$
h = 15^{\circ}(12-LAT)
$${#eq-Hour-Angle}

## Stefan Boltzman Law Grey Body Adjusted

$$
E_g = \epsilon\sigma_b T^4 + (1-\epsilon) * (SW\downarrow+LW\downarrow)
$${#eq-Stefan-Boltzman-Law-Grey-Body-Adjusted}

## Stefan Boltzman Law Grey Body

$$
E_g = \epsilon\sigma_b T^4
$${#eq-Stefan-Boltzman-Law-Grey-Body}

## Stefan Boltzman Law

$$
E_b = \sigma_b T^4
$${#eq-Stefan-Boltzman-Law}

## Surface Energy Balance Ice

$$
\color{orange}{R_n} = \color{red}{H} + \color{blue}{LE} + \color{green}{\Delta S} + \color{grey}{\Delta M}
$${#eq-Surface-Energy-Balance-Ice}

## Surface Energy Balance No Mass

$$
\color{orange}{R_n} = \color{red}{H} + \color{blue}{LE} + \color{purple}{G}
$${#eq-Surface-Energy-Balance-No-Mass}

## Surface Energy Balance Storage

$$
\color{orange}{R_n} = \color{red}{H} + \color{blue}{LE} + \color{purple}{G} + \color{green}{\Delta S}
$${#eq-Surface-Energy-Balance-Storage}

## Surface Energy Balance

$$
R_n = H + LE + G + \Delta S
$${#eq-Surface-Energy-Balance}

## Tetens

$$
P_v^* = 6.112\exp{17.62\frac{T_a}{243.12+T_a}}
$${#eq-Tetens}

## Thermal Admittance v Temperature

$$
\Delta T_s = \frac{\Delta H_g}{\mu}
$${#eq-Thermal-Admittance-v-Temperature}

## Thermal Admittance

$$
\mu = \sqrt{k C}
$${#eq-Thermal-Admittance}

## Thermal Diffusivity

$$
K = \frac{k}{C}
$${#eq-Thermal-Diffusivity}

## LMST

$$
LMST = (TZ) + (\lambda-TZ_{m})\frac{4}{60}
$${#eq-LMST}

## LAT

$$
LAT = LMST-\Delta LAT
$${#eq-LAT}

## Delta LAT

$$
\begin{eqnarray}\Delta LAT = & 229.18[0.000075+0.001868\cos(\gamma)-0.032077\sin(\gamma) \\             & -0.014615\cos(2\gamma)-0.040849\sin(2\gamma)]\end{eqnarray}
$${#eq-Delta-LAT}

## Weins Law

$$
\lambda_{max} = \frac{b}{T}
$${#eq-Weins-Law}

