project:
  type: website
  output-dir: docs
  # pre-render: 
  #   - _code/MakeKeys.py
  #   - _code/SummaryLists.py
  #   - _code/RefreshData.py
  # post-render: _code/MoveKeys.py
  resources: www

website:
  title: "Microscale Weather and Climate"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
  #     # - href: Lectures.qmd
  #     #   text: Lectures
  #     # - href: Labs.qmd
  #     #   text: Lab Assignments
    right:
      - icon: github
        href: https://github.com/June-Skeeter
        aria-label: Quarto GitHub
  sidebar:
    style: "docked"
    search: true
    contents: auto