project:
  type: website
  output-dir: docs
  pre-render: 
    - _code/MakeR.py
    - _code/SummaryLists.py
  #   - _code/RefreshData.py
  post-render: _Code/CopyCode.py
  resources: www

website:
  title: "Microscale Weather and Climate"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: Lectures/index.qmd
        text: Lectures
      - href: Assignments/index.qmd
        text: Assignments 
      - href: Study_Questions/index.qmd
        text: Study Questions 
    right:
      - icon: github
        href: https://github.com/June-Skeeter
        aria-label: Quarto GitHub
  sidebar:
    - title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - index.qmd
      - acknowledgement.qmd
      - Resources.qmd
      

    - title: "Lectures"
      style: "docked"
      background: light
      collapse-level: 1
      contents: Lectures

      
    - title: "Assignments"
      style: "docked"
      background: light
      collapse-level: 1
      contents: Assignments
      
    - title: "Study Questions"
      style: "docked"
      background: light
      collapse-level: 1
      contents: Study_Questions