---
title: "Assignment 1"
subtitle: "GEOS 300, 2024"
jupyter: python3
execute:
  keep-ipynb: true
echo: true
---

---

{{< include _Includes/Executables/Student_Info_py.qmd >}}

{{< include _Includes/Executables/Import_py.qmd >}}

{{< include _Includes/Executables/01/rubric_py.qmd >}}

### Question 1 

Below is an example showing the first few rows of the BB climate summary data.  What values do you see listed for Incoming and outgoing $SW$ in the first row of the table, are these values reasonable?  Why or why not?  

* Make suer to specify the units in your answer. Check the metadata provided [here](https://github.com/GEOS300/AssignmentData/blob/main/Climate_Summary_BB_Metadata.md) to make sure you understand the variable names and units.

{{< include _Includes/Executables/01/01_py.qmd >}}

#### Answer

More or less what we'd expect, but $SW_\downarrow$ shouldn't be less than $SW_\uparrow$, both should be ~0 zero, so indicates some lack of precision with the sensor (or perhaps a human made light source on site?)  Units $W m^{-2}$.


### Question 2 

We're going to be looking at some data from the January 2024 cold-snap (Jan 12 to Jan 19) and snowstorm (Jan 17-Jan 19) during which record low temperatures were observed and over 25cm of snow was received across the Metro Vancouver area.  The table below shows some descriptive statistics for key variables during this time period.  What was the range of air temperatures observed over this time period?  How does it compare to the range of soil temperatures observed?


{{< include _Includes/Executables/01/02_py.qmd >}}

#### Answer

The key point here is that $T_a$ has a much wider range (~15 $^{\circ} C$) compared to $T_s$ (~2.3 $^{\circ} C$) and that while $T_a$ was well bellow 0 $^{\circ} C$ for most of the period, $T_s$ didn't even drop below 2.5 $^{\circ} C$.

### Question 3

The plot below shows traces of the four radiation component, air & soil temperature, and relative humidity are.  Looking at the plot, what stands out to you?  Comment on the progression of each radiative component over time, using the temperature and humidity data to support your discussion and help explain any patterns you might see.  Do you see any issues in the data?  If so, what is a possible explanation?

{{< include _Includes/Executables/01/03_A_py.qmd >}}

#### Answer

Important to discuss how $LW$ varies as a function of temperature [$\downarrow$ (sky/clouds); $\uparrow$ (ground)] and how $SW_\downarrow$ & $SW_\uparrow$ are effected by cloud/snow.  Big issue on day of snowfall, radiometer is covered in snow; $SW_\downarrow$ should not be larger than $SW_\uparrow$


### Question 4

The plot below shows mean daily albedo.  What explains sharp increase on the 17th?

{{< include _Includes/Executables/01/04_py.qmd >}}

#### Answer

Fresh snow has a much higher albedo than either vegetated surfaces.  The significant snowfall event (30 cm) was more than enough to cover all the vegetation.

## Question 5

The maximum half-hourly $SW_\downarrow$ observed during this time period occurred between 12:30 and 13:00 on January 13th.  Using the equations from lecture, calculate the Local Apparent Time (LAT), solar declination $\delta$, solar zenith angle $Z$, and extraterrestrial irradiance $I_{ex}$ for the center point of this observation period (12:45).  Given the value of $I_{ex}$, compared to observed $SW_\downarrow$, what is the approximate bulk transmissivity ($\Psi_a$) coefficient of the atmosphere over CA-DBB at this point in time?  Given the value of $I_{ex}$, compared to observed $SW_\downarrow$, what is the approximate bulk transmissivity ($\Psi_a$) coefficient of the atmosphere over CA-DBB at this point in time?  

**Note**: you can find the site's Lat/Lon and time zone info in the CA-DBB station metadata file.


#### Answer

Equations are in lecture [4](https://geos300.github.io/Lectures/04.html#/title-slide) & [5](https://geos300.github.io/Lectures/04.html#/title-slide) with examples for time calculations in study question [2](https://geos300.github.io/Study_Questions/02.html),

Get the declination as follows:

{{< include ../_Equations/Solar-Declination.qmd >}}

And local Apparent time:

{{< include ../_Equations/TimeEquations.qmd >}}

And the zenith ($Z$) following:

{{< include ../_Equations/Solar-Zenith.qmd >}}

With the zenith an the fractional DOY, you can then get $I_{ex}$


{{< include ../_Equations/Extraterrestrial-Irradiance.qmd >}}

Use $Z$ and $I_{ex}$ to solve for $\Phi_a$

{{< include ../_Equations/Bulk-Transmissivity.qmd >}}

{{< include _Includes/Executables/01/05_A_py.qmd >}}

### Question 6

Now calculate $\Psi_a$ for 12:45 January 19; the observed value of $SW_\downarrow$ was between 12:30 and 13:00 was 58.375 W$^m{-2}$.  What explains the difference between these two days?

#### Answer

Same procedures as above, the key cause of the difference cloud cover.  Significantly more light is attenuated on the cloudy day, that light is reflected back to space by clouds (some is also absorbed) before making it to ground level.

{{< include _Includes/Executables/01/06_A_py.qmd >}}

### Question 7

Using the examples above as a template, calculate $R_n$ over the cold-snap.  Make a scatter plot showing $R_n$ on the y-axis and $SW_\downarrow$ on the x-axis.  Describe the relationship you.

#### Answer

First, must calculate $R_n$ following:

{{< include ../_Equations/Net-Radiation.qmd >}}

The relationship between the two: $SW_\downarrow$ is a significant driver of $R_n$, whien it is positive, it has a strong increasing effect on $R_n$ (but the slope modified by albedo).  However, the effects of $LW$ are also present in the $R_n$ signal, so it is not a simple linear relationship with $SW*$

{{< include _Includes/Executables/01/07_A_py.qmd >}}

### Question 8

Using the examples above as a template, create a new selection to see how typical summertime conditions compare to severe winter time conditions.  Change the selection period so that it spans July 12th to July 19th, 2023.  Provide summary statistics of the same variables as those shown above and produce plots like the ones shown above as well. Discuss how each of these variables during this mid-summer period compare to those from the cold-snap period.


#### Answer

Should reproduce **All** graphs and tables above so that there can be a well rounded comparison. **For plots:** make sure all axes limits are updated properly.  Key discussion points:

* Warmer weather (both $T_a$ and $T_s$).  While $T_a$ is still higher and more variable than $T_s$, it is important to note that $T_s$ in summer has a similar range as in winter.
    + Should also mention data gap in $T_s$ for full credit.

* More incoming $SW$ due to lower zenith angle and longer days.  Less variable due to less cloud cover.  Primarily clear sky conditions in summer
* More incoming/outgoing $LW$ due to higher temps of both ground and sky.  Less variable due to less cloud cover.  Primarily clear sky conditions in summer
* Albedo is lower due to lack of snow **and** green vegetation.
* $R_n$ vs $SW_\downarrow$ is more direct because of lack of snow and reduced variability in $LW$
* $RH$ is "lower" at times, but does not indicate drier atmosphere, because warm air can hold more water vapor



{{< include _Includes/Executables/01/08_1_py.qmd >}}

{{< include _Includes/Executables/01/08_2_py.qmd >}}

{{< include _Includes/Executables/01/08_3_py.qmd >}}

{{< include _Includes/Executables/01/08_4_py.qmd >}}

### Question 9

Find the timestamp of the observation interval when maximum $SW_\downarrow$ was observed for the mid-summer period.  You will use observations from this timestamp to answer each of the questions below.  **Note** our sites do not use daylight savings, so the UTC offset is fixed all year.  Use this information to calculate $I_{ex}$ and $\Psi_a$ for the mid-point of this observation period.  Discus how these two values compare between this observation, and the observation spanning between 12:30 and 13:00 on January 13th of 2024.  How does the magnitude differ and why does the relative timing of the maximum daily $SW_\downarrow$ differ?

#### Answer

Same procedures as question 5 for calculations.  Key discussion points:

* The magnitude of $I_{ex}$ differs because of the solar declination $\delta$ change giving us a lower zenith angle $z$ and therefore more concentrated solar beam (closer to $I_0$), despite the fact that the earth is slightly farther from the sun during the northern hemisphere summer.  

* $Psi_a$ is higher because the atmosphere has higher moisture content in the summer along with higher particulate matter content (this was discussion point from lecture).  This is interesting, because although the path length is much shorter in for this observation period than in winter, overall attenuation of the solar beam during this timestamp (~19%) exceeded that at 12:45 January 13th (~15%).  This highlights the impacts of air quality and water vapor content.

* The timing of the maximum differs because:
    1. $\Delta LAT$ changes through the year.  Not because of DST; as the sites don't use it. Local apparent time  
    2. Part of it is "randomness" due to cloud conditions 
        + explanation not needed for full credit: the 17th had some patchy cloud cover as indicated by the jumpiness of the SW trace on this day.  If there are clouds blocking the solar beam's path to the radiometer but some large reflective clouds to the north, some "excess" $SW$ reelected off the cloud can hit the radiometer and boost $SW_\downarrow$ a bit.

{{< include _Includes/Executables/01/09_A_py.qmd >}}

### Question 10

Approximately 42% of the energy in the short-wave is within the PAR band (Photosynthetically active radiation that can be used by plants to perform photosynthesis). Based on this assumption, calculate the energy available to plants (also called: photosynthetic photon flux density, PPFD) at noon in $\mu mol m^{-2}s^{-1}$. You can use the wavelength of yellow light ($\lambda 0 0.55 \mu m$) for your estimate.
**Hint**: Consult examples in reading package for radiation geometry.

#### Answer

Solve for the frequency of yellow light: 

{{< include ../_Equations/Frequency.qmd >}}

Then the energy, where h=6.63∗10−34Js

{{< include ../_Equations/Energy-of-Photon.qmd >}}

Then scale by 42% to estimate PAR and get total number of photons.  Finally convert to umol with Avogadro's number.

{{< include _Includes/Executables/01/10_A_py.qmd >}}

### Question 11

Let's assume the surface emissivity at CA-DBB is $\epsilon = 0.95$.  Using this assumption and the Stephan Boltzman law for grey bodies, estimate temperature of the land surface at CA-DBB for the time period identified above in question 9.

#### Answer

{{< include ../_Equations/Stefan-Boltzman-Law-Grey-Body.qmd >}}

{{< include _Includes/Executables/01/11_A_py.qmd >}}


### Question 12

Now use the same equation to estimate the "apparent" radiative sky temperature ($T_k$) from $LW_{\downarrow}$ for this timestamp.  "Apparent" means you should assume $\epsilon{a} = 1.0$. How would you interpret $T_k$?

#### Answer

Same calculations as above, but with $\epsilon{a} = 1.0$.  This is assuming the sky is a black body (not really).  This would be the temperature if the sky were a perfect absorber/emitter and not transparent to $LW$.


{{< include _Includes/Executables/01/12_A_py.qmd >}}

### Question 13

Using measured $LW_{\downarrow}$ and measured air temperature $T_a$, calculate the actual bulk emissivity of the atmosphere $\varepsilon_{a}$ at noon? [2]

#### Answer

Plug $LW$ into $E_g$ and using $T_a$ solve for $\epsilon$

{{< include ../_Equations/Stefan-Boltzman-Law-Grey-Body.qmd >}}


{{< include _Includes/Executables/01/13_A_py.qmd >}}



### Question 14

Using the Prata (1996) equation from lecture and measured $T_a$ and $RH$, what is the calculated apparent emissivity of the atmosphere and the calculated estimate of $LW_{\downarrow}$? How well do these approximations match with what we actually observed?

#### Answer

The approximation below will get pretty close (within about a couple percent) for clear sky conditions.  Won't work as well with cloud cover.  Calculate Parata (1996) as:

{{< include ../_Equations/Prata.qmd >}}

where you can use the Tetens equation to get $P_v^*$

{{< include ../_Equations/Prata.qmd >}}

{{< include _Includes/Executables/01/14_A_py.qmd >}}

